Ignore hartid in single-hart mode.
rust-embedded/riscv-rt pull request #126
Opened 2023-11-02 17:20 UTC by kevin-vigor

Don't bother checking hart ID on startup in single-hart mode. Allows use of cores with unusual mhartid values and saves a few instructions.

2023-11-03 12:02 UTC, romancardenas requested changes
Thanks for your PR! I left you a few comments.

The code becomes a bit more complex but I don't see the performance benefits of this PR. Can you review my suggestions and push a new commit?

2023-11-03 12:02 UTC, romancardenas commented on src/lib.rs
>      if _mp_hook(hartid) {
It would make sense to remove this check for single HART, and always call pre_init. That would be a slight improvement

2023-11-08 21:28 UTC, kevin-vigor commented on src/lib.rs
> +#[cfg(any(feature = "s-mode", feature = "single-hart"))]
That was clearly an error, thanks for the catch

2023-11-08 21:30 UTC, kevin-vigor commented on src/lib.rs
> +pub extern "Rust" fn default_mp_hook(_hartid: usize) -> bool {
I am actually working on a custom part where mhartid is non-zero even though there is only one hart for... reasons

This is the primary motivation for this change, TBH, but it does incidentally also remove unneeded mhartid reads from the single-hart mode, so I think it is a (small) general improvement

2023-11-08 21:32 UTC, kevin-vigor commented on src/lib.rs
>      if _mp_hook(hartid) {
Done, thanks!

2023-11-09 16:09 UTC, romancardenas commented on src/lib.rs
> +#[cfg(not(feature = "single-hart"))]
I think this should be `#[cfg(not(any(feature = "s-mode", feature = "single-hart"))]`, as it is only used in multi-hart machine mode.

2023-11-09 16:21 UTC, romancardenas commented
LGMT! Please, look at my last comment and add a short description of your PR in `CHANGELOG.md`.

2023-11-09 18:05 UTC, romancardenas approved these changes

2023-11-09 18:27 UTC, merged