update to riscv 0.7
rust-embedded/riscv-rt pull request #79
Opened 2021-09-18 13:57 UTC by smsxgli

hi everyone, I am a new guy with both github, rust and riscv, and this is my first PR, so if I miss something or do something wrong, please let me know (and forgive my poor english, since I am not a native speaker).
crate `riscv` v0.7 solved link error about [`different hardware float abi`](https://github.com/rust-embedded/riscv/issues/85), but riscv-rt still depend on `riscv` v0.6.

2021-09-18 14:28 UTC, Disasm requested changes
Thank you! Looks good overall, but there are a few issues :)

2021-09-18 14:28 UTC, Disasm commented on build.rs
> +    if target.starts_with("riscv") && env::var_os("CARGO_FEATURE_INLINE_ASM").is_none() {
The `inline-asm` feature cannot be used here: riscv-rt assembly library is always linked to, it cannot be inlined.

2021-09-18 14:28 UTC, Disasm commented on assemble.sh
> -for ext in i ic im imc
M extension support is not present in the resulting scripts for some reason. We still need it :)

2021-09-18 15:26 UTC, smsxgli commented on build.rs
> +    if target.starts_with("riscv") && env::var_os("CARGO_FEATURE_INLINE_ASM").is_none() {
Yeah, I found it, but we can make use the `global_asm` feature in nightly build, I tried it, but since I am not familiar with rust, I processed the conditional compilation manually(split the asm.S file to asm64.s and asm32.s), and using macro `global_asm!` to inline them. I thought this can be `inline-asm`.

2021-09-18 15:28 UTC, Disasm commented on build.rs
> +    if target.starts_with("riscv") && env::var_os("CARGO_FEATURE_INLINE_ASM").is_none() {
There is no plans to use `global_asm` currently, we only use `asm.S`.

2021-09-18 15:37 UTC, smsxgli commented on assemble.sh
> -for ext in i ic im imc
Well, I did not known that. You see, I just copy this from `riscv` crate.  So,  Adding these extensions to the build script may be a solution? Just like this:
`riscv64-unknown-elf-gcc -c -mabi=ilp32 -march=rv32im asm.S -o bin/$crate.o
ar crs bin/riscv32i-unknown-none-elf.a bin/$crate.o`
`riscv64-unknown-elf-gcc -c -mabi=ilp32 -march=rv32imc asm.S -o bin/$crate.o
ar crs bin/riscv32ic-unknown-none-elf.a bin/$crate.o`
or append `if ifc ...` to `ext`?

2021-09-18 15:40 UTC, smsxgli commented on build.rs
> +    if target.starts_with("riscv") && env::var_os("CARGO_FEATURE_INLINE_ASM").is_none() {
OK, I know that. But can I know why this crate decided not to use `global_asm`? Dose it have some disadvantages?

2021-09-18 15:40 UTC, Disasm commented on assemble.sh
> -for ext in i ic im imc
Whatever you like as long as it's correct

2021-09-18 15:41 UTC, Disasm commented on build.rs
> +    if target.starts_with("riscv") && env::var_os("CARGO_FEATURE_INLINE_ASM").is_none() {
It doesn't make sense. With `global_asm` you will need two implementations: one for those who want to use `global_asm` and `asm.S` for those who don't. And since there is no profit from using `global_asm`, it's better to use a single implementation.

2021-09-18 15:42 UTC, smsxgli commented on assemble.sh
> -for ext in i ic im imc
OK, I will work on it later. Thanks for your help and reply!

2021-09-18 20:12 UTC, almindor requested changes

2021-09-18 20:12 UTC, almindor commented on assemble.ps1
> -$extension_sets = @("i", "im", "ic", "imc")
Why this change? It seems cleaner to me in the old code.

2021-09-18 20:12 UTC, almindor commented on build.rs
> +        target.retain_extensions("ifdc");
You need to keep `m` here as well AFAIK

2021-09-19 02:27 UTC, smsxgli commented on build.rs
> +        target.retain_extensions("ifdc");
OK

2021-09-19 02:43 UTC, smsxgli commented on assemble.ps1
> -$extension_sets = @("i", "im", "ic", "imc")
Sorry for that, but the the `abi` changed too. So I just copy this build script from `riscv` crate. I am trying on it.

2021-09-19 05:50 UTC, smsxgli commented on build.rs
> +    if target.starts_with("riscv") && env::var_os("CARGO_FEATURE_INLINE_ASM").is_none() {
Well, just a thought, what about adding something into `build.rs` to generate a `asm_inline.s` from `asm.S`,and then using this generated file with `global_asm`?

2021-09-19 05:58 UTC, Disasm commented on build.rs
> +    if target.starts_with("riscv") && env::var_os("CARGO_FEATURE_INLINE_ASM").is_none() {
But what profit you can get with this approach?

2021-09-19 06:08 UTC, smsxgli commented on build.rs
> +    if target.starts_with("riscv") && env::var_os("CARGO_FEATURE_INLINE_ASM").is_none() {
Well, totally git rid of `gcc` toolchain? Every thing can build from source with Rust it self? Maybe this thought is unpractical, and maintain more code for it is a totally wasting?

2021-09-19 06:14 UTC, Disasm commented on build.rs
> +    if target.starts_with("riscv") && env::var_os("CARGO_FEATURE_INLINE_ASM").is_none() {
I believe you can **use** this crate without gcc toolchain. It is only required for updating the blobs.
Actually there is a way to implement what you want, but it's more complicated. You can take a look at https://github.com/rust-embedded/cortex-m/. It's still more useful for `riscv` than `riscv-rt`...

2021-09-19 06:17 UTC, Disasm approved these changes
Looks good to me, thanks!

2021-09-19 06:17 UTC, smsxgli commented on build.rs
> +    if target.starts_with("riscv") && env::var_os("CARGO_FEATURE_INLINE_ASM").is_none() {
OK, I will take a look. Thank you!

2021-09-19 21:07 UTC, almindor approved these changes

2021-09-19 21:07 UTC, almindor commented
bors r+

2021-09-19 21:10 UTC, merged