Add boot_argument(), returns the value an `a*` register had at boot time
rust-embedded/riscv-rt pull request #94
Opened 2022-06-25 00:15 UTC by SimonSapin

Fixes https://github.com/rust-embedded/riscv-rt/issues/92

With this PR, the code below succeeds in QEMU and [`Fdt`](https://docs.rs/fdt/latest/fdt/) can be used to find the address of the simulated UART that prints to stdout on the host.

```rust
use fdt::Fdt;

pub fn parse() -> Fdt<'static> {
    /// https://doc.coreboot.org/arch/riscv/index.html#stage-handoff-protocol
    const FDT_ARG_POSITION: usize = 1;
    let ptr = riscv_rt::boot_argument(FDT_ARG_POSITION).unwrap() as *const u8;
    unsafe { Fdt::from_ptr(ptr).expect("Failed to parse FDT") }
}
```

2022-06-25 00:19 UTC, SimonSapin commented
This unconditionally reserves 8 * XLEN in `.data`. Hopefully that’s considered cheap enough to have even when not used. 8 is the total number of argument registers that exist, but since QEMU / coreboot only use 3 we could also reduce to that.

2022-06-25 01:54 UTC, almindor submitted a review, later dismissed
this seems sensible to me. I'll wait for @Disasm to approve as well tho.

2022-06-25 05:36 UTC, Disasm requested changes
This will not work well in multi-core environments since multiple cores will execute the same code at the same time. If different argument values are passed on different cores, we will get garbage in the end.

2022-06-25 07:27 UTC, Disasm commented
I checked binary sizes and this PR adds 44 bytes for `riscv32imac-unknown-none-elf` while passing a0..a2 to main adds 12 bytes

2022-06-25 07:49 UTC, SimonSapin commented
I’d added a branch on hartid that I believe should fix the multicore issue.

What does the source code look like for passing to main in your comparison?

2022-06-25 07:52 UTC, Disasm commented
I created a draft PR for this: https://github.com/rust-embedded/riscv-rt/pull/95 currently the proc-macro part is missing.

2022-06-25 08:26 UTC, SimonSapin commented on asm.S
> +    fence rw, rw
I’m not confident about this (single) fence, or about using plain reads in `fn boot_arguments`.

At first I started emulating the behavior of `AtomicUsize`: https://rust.godbolt.org/z/3djWjhPcG. But why is the `fence` instruction placed before stores and after loads? I’d expected fences to be between things in order to separate them.

On the Rust size I ended up with this, since [`AtomicUsize` is disabled on targets without the `A` extension](https://github.com/rust-lang/rust/pull/98333). The [`portable-atomic`](https://crates.io/crates/portable-atomic) crate would be another option for doing the same.

```rust
/// Simulate AtomicUsize::load(Ordering::Acquire)
unsafe fn atomic_load(ptr: *const usize) -> usize {
    let value;

    // Only lw v.s. ld changes but asm! wants a string literal
    #[cfg(target_pointer_width = "32")]
    core::arch::asm!(
        "fence r, rw",
        "lw {value}, 0({ptr})",
        ptr = in(reg) ptr,
        value = out(reg) value,
    );
    #[cfg(not(target_pointer_width = "32"))]
    core::arch::asm!(
        "fence r, rw",
        "ld {value}, 0({ptr})",
        ptr = in(reg) ptr,
        value = out(reg) value,
    );
    value
}
```

2022-06-25 08:41 UTC, Disasm commented on asm.S
> +    fence rw, rw
Position of fence instructions depends on the ordering. With `SeqCst` you get fences before and after the load.

2022-06-29 12:08 UTC, SimonSapin commented
Closing in favor of https://github.com/rust-embedded/riscv-rt/pull/95

2022-06-29 12:08 UTC, closed without merging